In [80]:
import pandas as pd

In [81]:
defense= pd.read_csv("roster/defense.csv")
offense= pd.read_csv("roster/offense.csv")
special= pd.read_csv("roster/special.csv")

In [82]:
players_df = pd.concat([defense,offense])
players_df = pd.concat([players_df,special])
players_df = players_df.drop(columns=['Unnamed: 0']).reset_index(drop=True)

In [84]:
import re 
  
def remove(list): 
    pattern = '[0-9]'
    list = [re.sub(pattern, '', i) for i in list] 
    return list
players_df["FullName"]=remove(players_df.Name)

In [86]:
first = []
last = []

test = [name.split for name in players_df.FullName]
for name in players_df.FullName:
    name_split = name.split(' ')
    if len(name_split)<3:
        
        first.append(name_split[0])
        last.append(name_split[1])
    else:
        first.append(name_split[0])
        last.append(name_split[1]+" " +name_split[2])

players_df["First Name"] = first
players_df["Last Name"] = last

In [88]:
team_abv_list = []
for i in range(0,len(players_df.team)):
    x = True
    for j in range(0,len(team_df.Team)):
        
        if players_df.team[i] in team_df.Team[j] and x == True:
                   
            team_abv_list.append(team_df.TM[j])
            x=False
                   
            
            
players_df['TeamID']=team_abv_list
players_df = players_df.rename(columns={"Name":"PlayerID"})

In [112]:


players_df.to_csv("temp/players_df.csv")

In [97]:
metrics

,Name,Height,Weight,Forty Yard Dash,Shuttle Time,Vertical Jump,Broad Jump,Bench Press,Cone Drill
0,Tom Brady,"6' 4""",225 lbs,5.28 sec,4.38 sec,24.5 in,99 in,NaN,7.20 sec
1,Drew Brees,"6' 0""",209 lbs,4.83 sec,4.21 sec,32.0 in,105 in,NaN,7.09 sec
2,Will Allen,"5' 10""",192 lbs,4.58 sec,4.25 sec,36.0 in,115 in,NaN,7.06 sec
3,Reggie Wayne,"6' 0""",203 lbs,4.45 sec,NaN,36.0 in,NaN,NaN,NaN
4,Steve Smith,"5' 9""",195 lbs,4.44 sec,4.19 sec,38.0 in,120 in,NaN,6.68 sec
...,...,...,...,...,...,...,...,...,...
3646,Evan Weaver,"6' 2""",237 lbs,4.76 sec,4.21 sec,32.0 in,117 in,15 reps,7.02 sec
3647,Casey Toohill,"6' 4""",250 lbs,4.62 sec,4.21 sec,39.0 in,126 in,17 reps,7.08 sec
3648,Mykal Walker,"6' 3""",230 lbs,4.65 sec,4.25 sec,33.0 in,122 in,20 reps,7.09 sec
3649,Chapelle Russell,"6' 2""",236 lbs,4.69 sec,4.41 sec,35.0 in,121 in,21 reps,7.38 sec
3650,Justin Strnad,"6' 3""",238 lbs,4.74 sec,4.49 sec,29.0 in,113 in,NaN,NaN

In [107]:
players_df.head()

,PlayerID,POS,Age,HT,WT,Exp,College,team,FullName,First Name,Last Name,TeamID
0,Mario Addison97,DE,32,"6' 3""",260 lbs,10,Troy,Bills,Mario Addison,Mario,Addison,BUF
1,Bryan Cox Jr.94,DE,25,"6' 3""",270 lbs,4,Florida,Bills,Bryan Cox Jr.,Bryan,Cox Jr.,BUF
2,AJ Epenesa57,DE,21,"6' 6""",280 lbs,R,Iowa,Bills,AJ Epenesa,AJ,Epenesa,BUF
3,Jerry Hughes55,DE,31,"6' 2""",254 lbs,11,TCU,Bills,Jerry Hughes,Jerry,Hughes,BUF
4,Darryl Johnson92,DE,23,"6' 6""",253 lbs,2,North Carolina A&T,Bills,Darryl Johnson,Darryl,Johnson,BUF

In [92]:
#Player Metrics

In [96]:
metric = pd.read_csv("rotowire/cleaned_rotowire2.csv")

In [135]:
metrics = metric[["Name", "Height", "Weight", "Forty Yard Dash", "Shuttle Time", "Vertical Jump", "Broad Jump", "Bench Press", "Cone Drill"]]


metric_merge = metrics.merge(players_df, left_on='Name', right_on="FullName", how = 'inner')
metric_merge = metric_merge[["PlayerID","Name", "Height", "Weight", "Forty Yard Dash", "Shuttle Time", "Vertical Jump", "Broad Jump", "Bench Press", "Cone Drill"]]
metric_merge = metric_merge.drop(columns=['Name'])
metric_merge.to_csv("temp/metrics_df")

In [136]:
metric_merge

,PlayerID,Height,Weight,Forty Yard Dash,Shuttle Time,Vertical Jump,Broad Jump,Bench Press,Cone Drill
0,Tom Brady12,"6' 4""",225 lbs,5.28 sec,4.38 sec,24.5 in,99 in,NaN,7.20 sec
1,Drew Brees9,"6' 0""",209 lbs,4.83 sec,4.21 sec,32.0 in,105 in,NaN,7.09 sec
2,Jason Witten82,"6' 6""",263 lbs,4.65 sec,NaN,31.0 in,NaN,25 reps,NaN
3,Larry Fitzgerald11,"6' 3""",218 lbs,4.48 sec,4.28 sec,38.0 in,NaN,NaN,6.94 sec
4,Mike Williams81,"6' 5""",229 lbs,4.53 sec,4.31 sec,33.5 in,116 in,8 reps,6.90 sec
...,...,...,...,...,...,...,...,...,...
1551,Evan Weaver50,"6' 2""",237 lbs,4.76 sec,4.21 sec,32.0 in,117 in,15 reps,7.02 sec
1552,Casey Toohill52,"6' 4""",250 lbs,4.62 sec,4.21 sec,39.0 in,126 in,17 reps,7.08 sec
1553,Mykal Walker43,"6' 3""",230 lbs,4.65 sec,4.25 sec,33.0 in,122 in,20 reps,7.09 sec
1554,Chapelle Russell53,"6' 2""",236 lbs,4.69 sec,4.41 sec,35.0 in,121 in,21 reps,7.38 sec
1555,Justin Strnad23,"6' 3""",238 lbs,4.74 sec,4.49 sec,29.0 in,113 in,NaN,NaN

In [211]:
defense_df = pd.read_csv("stats/defense.csv")
kicking_df = pd.read_csv("stats/kicking.csv")
passing_df = pd.read_csv("stats/passing.csv")
punting_df = pd.read_csv("stats/punting.csv")
receiving_df = pd.read_csv("stats/receiving.csv")
returning_df = pd.read_csv("stats/returning.csv")
rushing_df = pd.read_csv("stats/rushing.csv")
scoring_df = pd.read_csv("stats/scoring.csv")

In [177]:
# defense_df = defense_df.drop(columns=["Unnamed: 0"])
kicking_df = kicking_df.drop(columns=["Unnamed: 0"])
passing_df = passing_df.drop(columns=["Unnamed: 0"])
punting_df = punting_df.drop(columns=["Unnamed: 0"])
receiving_df = receiving_df.drop(columns=["Unnamed: 0"])
returning_df = returning_df.drop(columns=["Unnamed: 0"])
rushing_df = rushing_df.drop(columns=["Unnamed: 0"])
scoring_df = scoring_df.drop(columns=["Unnamed: 0"])

KeyError: "['Unnamed: 0'] not found in axis"

In [154]:
defense_df.rename(columns={
    "('Unnamed: 0_level_0', 'GP')":"GP",
    "('Tackles', 'SOLO')":"TACKLES_SOLO",
    "('Tackles', 'AST')":"TACKLES_AST",
    "('Tackles', 'TOT')":"TACKLES_TOT",
    "('Sacks', 'SACK')":"SACKS",
    "('Sacks', 'SCKYDS')":"SACKS_SCKYDS",
    "('Sacks', 'TFL')":"SACKS_TFL",
    "('Interceptions', 'PD')":"INTERCEPTIONS_PD",
    "('Interceptions', 'INT')":"INTERCEPTIONS_INT",
    "('Interceptions', 'YDS')":"INTERCEPTIONS_YDS",
    "('Interceptions', 'LNG')":"INTERCEPTIONS_LNG",
    "('Interceptions', 'TD')":"INTERCEPTIONS_TD",
    "('Fumbles', 'FF')":"FUMBLES_FF",
    "('Fumbles', 'FR')":"FUMBLES_FR",
    "('Fumbles', 'FTD')":"FUMBLES_FTD",
    "('Unnamed: 15_level_0', 'KB')":"KB"
                         }, inplace=True)

In [179]:
defense_df = defense_df.drop(columns=['class','team'])

KeyError: "['class'] not found in axis"

In [170]:
for i in range(0,len(defense_df.Name)):
    defense_df.Name[i]=defense_df.Name[i].replace(defense_df.Name[i].split(" ").pop(-1),"").strip()

defense_df

C:\Users\chand\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Name,GP,TACKLES_SOLO,TACKLES_AST,TACKLES_TOT,SACKS,SACKS_SCKYDS,SACKS_TFL,INTERCEPTIONS_PD,INTERCEPTIONS_INT,INTERCEPTIONS_YDS,INTERCEPTIONS_LNG,INTERCEPTIONS_TD,FUMBLES_FF,FUMBLES_FR,FUMBLES_FTD,KB
0,Tremaine Edmunds,16,66,49,115,1.5,11,11.5,9,1,0,0,0,0,0,0,0
1,Jordan Poyer,16,71,36,107,1.0,5,5.5,3,2,0,0,0,3,3,0,0
2,Matt Milano,15,65,36,101,1.5,12,9.5,9,0,0,0,0,1,1,0,0
3,Levi Wallace,16,66,10,76,0.0,0,4.0,9,2,2,2,0,0,0,0,0
4,Micah Hyde,16,50,22,72,0.0,0,1.5,2,1,0,0,0,2,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,Russell Wilson,16,1,0,1,0.0,0,0.0,0,0,0,0,0,0,0,0,0
1485,George Fant,16,1,0,1,0.0,0,0.0,0,0,0,0,0,0,0,0,0
1486,Malik Turner,15,1,0,1,0.0,0,0.0,0,0,0,0,0,1,0,0,0
1487,Ryan Neal,3,1,0,1,0.0,0,0.0,0,0,0,0,0,0,0,0,0
1488,Duane Brown,12,1,0,1,0.0,0,0.0,0,0,0,0,0,0,0,0,0

In [174]:
defense_df = defense_df.merge(players_df, left_on='Name',right_on="FullName", how = 'inner')

In [184]:
defense_df.head(1)

,Name,GP,TACKLES_SOLO,TACKLES_AST,TACKLES_TOT,SACKS,SACKS_SCKYDS,SACKS_TFL,INTERCEPTIONS_PD,INTERCEPTIONS_INT,...,Age,HT,WT,Exp,College,team,FullName,First Name,Last Name,TeamID
0,Tremaine Edmunds,16,66,49,115,1.5,11,11.5,9,1,...,22,"6' 5""",250 lbs,3,Virginia Tech,Bills,Tremaine Edmunds,Tremaine,Edmunds,BUF

In [188]:
defense_df = defense_df.drop(columns=["Age","HT","WT","Exp","College","team","FullName","First Name","Last Name","TeamID",'POS','Name'])
defense_df.to_csv("temp/defense_df")

In [212]:
kicking_df = kicking_df.rename(columns={
    "('Unnamed: 0_level_0', 'GP')":"GP",
    "('Field Goals', 'FGM')":"FGM",
    "('Field Goals', 'FGA')":"FGA",
    "('Field Goals', 'FG%')":"FG%",
    "('Field Goals', 'LNG')":"LNG",
    "('Field Goals', '1-19')":"FG_01-19",
    "('Field Goals', '20-29')":"FG_20-29",
    "('Field Goals', '30-39')":"FG_30-39",
    "('Field Goals', '40-49')":"FG_40-49",
    "('Field Goals', '50+')":"FG_50+",
    "('Extra points', 'XPM')":"XPM",
    "('Extra points', 'XPA')":"XPA",
    "('Extra points', 'XP%')":"XP%"})

In [213]:
id_df = players_df[['PlayerID','FullName']]

In [214]:
for i in range(0,len(kicking_df.Name)):
    kicking_df.Name[i]=kicking_df.Name[i].replace(kicking_df.Name[i].split(" ").pop(-1),"").strip()

kicking_df

C:\Users\chand\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0,Name,GP,FGM,FGA,FG%,LNG,FG_01-19,FG_20-29,FG_30-39,FG_40-49,FG_50+,XPM,XPA,XP%,class,team
0,0,Stephen Hauschka,16,22,28,78.6,51,0-0,5-5,7-8,9-10,1-5,30,32,93.8,Kicking,Bills
1,1,Jason Sanders,16,23,30,76.7,54,0-0,7-7,8-9,5-9,3-5,29,30,96.7,Kicking,Dolphins
2,2,Nick Folk,7,14,17,82.4,51,1-1,5-5,3-3,4-7,1-1,12,12,100.0,Kicking,Patriots
3,3,Stephen Gostkowski,4,7,8,87.5,41,0-0,3-3,3-3,1-2,0-0,11,15,73.3,Kicking,Patriots
4,4,Mike Nugent,4,5,8,62.5,37,0-0,3-4,2-3,0-1,0-0,15,16,93.8,Kicking,Patriots
5,5,Kai Forbath,1,1,1,100.0,23,0-0,1-1,0-0,0-0,0-0,1,2,50.0,Kicking,Patriots
6,6,Sam Ficken,15,19,27,70.4,54,0-0,2-2,7-8,7-11,3-6,23,26,88.5,Kicking,Jets
7,7,Justin Tucker,16,28,29,96.6,51,0-0,8-8,9-9,10-11,1-1,57,59,96.6,Kicking,Ravens
8,8,Randy Bullock,16,27,31,87.1,57,0-0,10-10,6-6,10-12,1-3,24,25,96.0,Kicking,Bengals
9,9,Austin Seibert,16,25,29,86.2,53,0-0,6-6,9-9,9-12,1-2,30,35,85.7,Kicking,Browns
10,10,Chris Boswell,16,29,31,93.5,51,1-1,11-11,7-7,9-10,1-2,28,28,100.0,Kicking,Steelers
11,11,Ka'imi Fairbairn,16,20,25,80.0,54,0-0,5-5,8-8,4-6,3-6,40,45,88.9,Kicking,Texans
12,12,Adam Vinatieri,12,17,25,68.0,55,0-0,6-7,6-6,3-7,2-5,22,28,78.6,Kicking,Colts
13,13,Chase McLaughlin,4,5,6,83.3,50,1-1,1-1,1-1,0-1,2-2,11,11,100.0,Kicking,Colts
14,14,Josh Lambo,16,33,34,97.1,56,0-0,12-12,9-9,8-9,4-4,19,20,95.0,Kicking,Jaguars
15,15,Cairo Santos,5,4,9,44.4,53,0-0,0-0,1-3,2-3,1-3,12,12,100.0,Kicking,Titans
16,16,Cody Parkey,3,3,3,100.0,51,0-0,0-0,0-0,2-2,1-1,5,6,83.3,Kicking,Titans
17,17,Ryan Succop,6,1,6,16.7,31,0-0,0-0,1-1,0-4,0-1,24,25,96.0,Kicking,Titans
18,18,Greg Joseph,2,0,0,0.0,0,0-0,0-0,0-0,0-0,0-0,9,9,100.0,Kicking,Titans
19,19,Brandon McManus,16,29,34,85.3,53,0-0,6-6,9-9,10-12,4-7,25,26,96.2,Kicking,Broncos
20,20,Harrison Butker,16,34,38,89.5,56,0-0,9-9,9-10,13-13,3-6,45,48,93.8,Kicking,Chiefs
21,21,Daniel Carlson,16,19,26,73.1,48,0-0,8-8,5-6,6-10,0-2,34,36,94.4,Kicking,Raiders
22,22,Michael Badgley,8,13,16,81.3,49,0-0,5-5,2-2,6-8,0-1,19,19,100.0,Kicking,Chargers
23,23,Ty Long,16,7,9,77.8,51,0-0,0-0,2-3,4-5,1-1,9,9,100.0,Kicking,Chargers
24,24,Chase McLaughlin,4,6,9,66.7,50,0-0,2-2,2-2,1-4,1-1,7,7,100.0,Kicking,Chargers
25,25,Brett Maher,13,20,30,66.7,63,0-0,9-9,6-8,1-5,4-8,36,36,100.0,Kicking,Cowboys
26,26,Kai Forbath,3,10,10,100.0,50,0-0,1-1,1-1,7-7,1-1,10,10,100.0,Kicking,Cowboys
27,27,Aldrick Rosas,16,12,17,70.6,45,0-0,6-6,5-6,1-4,0-1,35,39,89.7,Kicking,Giants
28,28,Jake Elliott,16,22,26,84.6,53,0-0,7-7,8-8,5-7,2-4,35,37,94.6,Kicking,Eagles
29,29,Dustin Hopkins,16,25,30,83.3,53,0-0,7-8,8-9,8-10,2-3,21,22,95.5,Kicking,Redskins
30,30,Eddy Pineiro,16,23,28,82.1,53,1-1,8-8,9-10,3-7,2-2,27,29,93.1,Kicking,Bears
31,31,Matt Prater,16,26,31,83.9,56,0-0,11-11,2-3,6-9,7-8,35,36,97.2,Kicking,Lions
32,32,Mason Crosby,16,22,24,91.7,54,1-1,2-2,11-11,7-8,1-2,40,41,97.6,Kicking,Packers
33,33,Dan Bailey,16,27,29,93.1,50,0-0,10-10,9-9,5-7,3-3,40,44,90.9,Kicking,Vikings
34,34,Younghoe Koo,8,23,26,88.5,50,0-0,6-6,9-10,7-9,1-1,15,16,93.8,Kicking,Falcons
35,35,Matt Bryant,7,9,14,64.3,52,0-0,1-1,3-4,3-3,2-6,14,15,93.3,Kicking,Falcons
36,36,Joey Slye,16,25,32,78.1,55,0-0,4-5,5-5,8-11,8-11,31,35,88.6,Kicking,Panthers
37,37,Wil Lutz,16,32,36,88.9,58,1-1,9-9,6-6,13-15,3-5,48,49,98.0,Kicking,Saints
38,38,Matt Gay,16,27,35,77.1,58,0-0,6-6,5-7,11-14,5-8,43,48,89.6,Kicking,Buccaneers
39,39,Zane Gonzalez,16,31,35,88.6,54,0-0,12-12,12-13,5-8,2-2,34,35,97.1,Kicking,Cardinals
40,40,Greg Zuerlein,16,24,33,72.7,58,0-0,7-7,7-8,5-11,5-7,42,42,100.0,Kicking,Rams
41,41,Robbie Gould,13,23,31,74.2,47,0-0,9-9,8-10,6-8,0-4,41,42,97.6,Kicking,49ers
42,42,Chase McLaughlin,3,7,8,87.5,48,0-0,2-2,1-1,4-5,0-0,8,8,100.0,Kicking,49ers
43,43,Jason Myers,16,23,28,82.1,54,0-0,6-6,11-11,4-7,2-4,40,44,90.9,Kicking,Seahawks

In [215]:
kicking_df = kicking_df.merge(id_df, left_on='Name',right_on="FullName", how = 'inner')
#kicking_df.drop(columns=['Unnamed: 0', 'Name', 'class', 'team', 'FullName'])

In [219]:
kicking_df = kicking_df.drop(columns=["Unnamed: 0","class","team","FullName","Name"])
kicking_df.to_csv("temp/kicking_df.csv")

In [231]:
# defense_df = pd.read_csv("stats/defense.csv")
# kicking_df = pd.read_csv("stats/kicking.csv")
passing_df = pd.read_csv("stats/passing.csv")
punting_df = pd.read_csv("stats/punting.csv")
receiving_df = pd.read_csv("stats/receiving.csv")
returning_df = pd.read_csv("stats/returning.csv")
rushing_df = pd.read_csv("stats/rushing.csv")
scoring_df = pd.read_csv("stats/scoring.csv")

In [232]:
passing_df = passing_df.drop(columns=['Unnamed: 0','class','team'])

In [233]:
for i in range(0,len(passing_df.Name)):
    passing_df.Name[i]=passing_df.Name[i].replace(passing_df.Name[i].split(" ").pop(-1),"").strip()

passing_df

C:\Users\chand\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Name,GP,CMP,ATT,CMP%,YDS,AVG,YDS/G,LNG,TD,INT,SACK,SYL,QBR,RTG
0,Josh Allen,16,271,461,58.8,3089,6.7,224.9,53,20,9,38,237,45.8,85.3
1,Matt Barkley,2,27,51,52.9,359,7.0,177.5,41,0,3,2,10,9.2,51.0
2,John Brown,15,1,1,100.0,28,28.0,73.0,28,1,0,0,0,100.0,158.3
3,Ryan Fitzpatrick,15,311,502,62.0,3529,7.0,251.5,51,20,13,40,209,64.7,85.5
4,Josh Rosen,6,58,109,53.2,567,5.2,96.7,40,1,5,16,93,19.4,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Jimmy Garoppolo,16,329,476,69.1,3978,8.4,252.5,75,27,13,36,237,60.2,102.0
98,Emmanuel Sanders,10,1,1,100.0,35,35.0,53.7,35,1,0,0,0,100.0,158.3
99,Dante Pettis,11,1,1,100.0,16,16.0,11.4,16,0,0,0,0,59.8,118.8
100,Russell Wilson,16,341,516,66.1,4110,8.0,278.3,60,31,5,48,319,69.4,106.3
101,Josh Gordon,5,0,1,0.0,0,0.0,27.8,0,0,1,0,0,0.0,0.0

In [236]:
id_df

PlayerID    2840
FullName    2840
dtype: int64

In [237]:
passing_df = passing_df.merge(id_df, left_on='Name',right_on="FullName", how = 'inner')

,Name,GP,CMP,ATT,CMP%,YDS,AVG,YDS/G,LNG,TD,INT,SACK,SYL,QBR,RTG,PlayerID,FullName
0,Josh Allen,16,271,461,58.8,3089,6.7,224.9,53,20,9,38,237,45.8,85.3,Josh Allen41,Josh Allen
1,Josh Allen,16,271,461,58.8,3089,6.7,224.9,53,20,9,38,237,45.8,85.3,Josh Allen17,Josh Allen
2,Matt Barkley,2,27,51,52.9,359,7.0,177.5,41,0,3,2,10,9.2,51.0,Matt Barkley5,Matt Barkley
3,John Brown,15,1,1,100.0,28,28.0,73.0,28,1,0,0,0,100.0,158.3,John Brown15,John Brown
4,Ryan Fitzpatrick,15,311,502,62.0,3529,7.0,251.5,51,20,13,40,209,64.7,85.5,Ryan Fitzpatrick14,Ryan Fitzpatrick
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Cooper Kupp,16,0,1,0.0,0,0.0,72.8,0,0,0,0,0,0.0,39.6,Cooper Kupp18,Cooper Kupp
86,Jimmy Garoppolo,16,329,476,69.1,3978,8.4,252.5,75,27,13,36,237,60.2,102.0,Jimmy Garoppolo10,Jimmy Garoppolo
87,Emmanuel Sanders,10,1,1,100.0,35,35.0,53.7,35,1,0,0,0,100.0,158.3,Emmanuel Sanders17,Emmanuel Sanders
88,Dante Pettis,11,1,1,100.0,16,16.0,11.4,16,0,0,0,0,59.8,118.8,Dante Pettis18,Dante Pettis
89,Russell Wilson,16,341,516,66.1,4110,8.0,278.3,60,31,5,48,319,69.4,106.3,Russell Wilson3,Russell Wilson

In [238]:
passing_df = passing_df.drop(columns=["Name","FullName"])
passing_df.to_csv("temp/passing_df.csv")

In [260]:
# defense_df = pd.read_csv("stats/defense.csv")
# kicking_df = pd.read_csv("stats/kicking.csv")
# passing_df = pd.read_csv("stats/passing.csv")
# punting_df = pd.read_csv("stats/punting.csv")
# receiving_df = pd.read_csv("stats/receiving.csv")
returning_df = pd.read_csv("stats/returning.csv")
# rushing_df = pd.read_csv("stats/rushing.csv")
scoring_df = pd.read_csv("stats/scoring.csv")

In [248]:
punting_df = punting_df.drop(columns=['Unnamed: 0','class','team'])

for i in range(0,len(punting_df.Name)):
    punting_df.Name[i]=punting_df.Name[i].replace(punting_df.Name[i].split(" ").pop(-1),"").strip()

punting_df = punting_df.merge(id_df, left_on='Name',right_on="FullName", how = 'inner')

punting_df = punting_df.drop(columns=["Name","FullName"])


receiving_df = receiving_df.drop(columns=['Unnamed: 0','class','team'])

for i in range(0,len(receiving_df.Name)):
    receiving_df.Name[i]=receiving_df.Name[i].replace(receiving_df.Name[i].split(" ").pop(-1),"").strip()

receiving_df = receiving_df.merge(id_df, left_on='Name',right_on="FullName", how = 'inner')

receiving_df = receiving_df.drop(columns=["Name","FullName"])

rushing_df = rushing_df.drop(columns=['Unnamed: 0','class','team'])

for i in range(0,len(rushing_df.Name)):
    rushing_df.Name[i]=rushing_df.Name[i].replace(rushing_df.Name[i].split(" ").pop(-1),"").strip()

rushing_df = rushing_df.merge(id_df, left_on='Name',right_on="FullName", how = 'inner')

rushing_df = rushing_df.drop(columns=["Name","FullName"])

C:\Users\chand\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\chand\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chand\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [252]:
punting_df.to_csv("temp/punting_df.csv")
receiving_df.to_csv("temp/receiving_df.csv")
rushing_df.to_csv("temp/rushing_df.csv")

scoring_df.rename({"Name":"test"})

scoring_df = scoring_df.rename({
    "('Unnamed: 0_level_0', 'GP')":"GP",
    "('Touchdowns', 'RUSH')":"TD_RUSH",
    "('Touchdowns', 'REC')":"TD_REC",
    "('Touchdowns', 'RET')":"TD_RET",
    "('Touchdowns', 'TD')":"TD",
    "('Scoring', 'FG')":"SCORING_FG",
    "('Scoring', 'PAT')":"SCORING_PAT",
    "('Scoring', '2PT')":"SCORING_2PT",
    "('Scoring', 'PTS')":"SCORING_PTS",
    "('Scoring', 'TP/G')":"SCORING_TP/G"})


returning_df = returning_df.rename({
    "('Unnamed: 0_level_0', 'GP')":"GP",
    "('Kickoffs', 'ATT')":"KO_ATT",
    "('Kickoffs', 'YDS')":"KO_YDS",
    "('Kickoffs', 'AVG')":"KO_AVG",
    "('Kickoffs', 'LNG')":"KO_LNG",
    "('Kickoffs', 'TD')":"KO_TD",
    "('Punts', 'ATT')":"PUNTS_ATT",
    "('Punts', 'YDS')":"PUNTS_YDS",
    "('Punts', 'AVG')":"PUNTS_AVG",
    "('Punts', 'LNG')":"PUNTS_LNG",
    "('Punts', 'TD')":"PUNTS_TD",
    "('Punts', 'FC')":"PUNTS_FC"
})

scoring_df = scoring_df.drop(columns=['Unnamed: 0','class','team'])

for i in range(0,len(scoring_df.Name)):
    scoring_df.Name[i]=scoring_df.Name[i].replace(scoring_df.Name[i].split(" ").pop(-1),"").strip()

scoring_df = scoring_df.merge(id_df, left_on='Name',right_on="FullName", how = 'inner')

scoring_df = scoring_df.drop(columns=["Name","FullName"])


returning_df = returning_df.drop(columns=['Unnamed: 0','class','team'])

for i in range(0,len(returning_df.Name)):
    returning_df.Name[i]=returning_df.Name[i].replace(returning_df.Name[i].split(" ").pop(-1),"").strip()

returning_df = returning_df.merge(id_df, left_on='Name',right_on="FullName", how = 'inner')

returning_df = returning_df.drop(columns=["Name","FullName"])

In [259]:
returning_df

,"('Unnamed: 0_level_0', 'GP')","('Kickoffs', 'ATT')","('Kickoffs', 'YDS')","('Kickoffs', 'AVG')","('Kickoffs', 'LNG')","('Kickoffs', 'TD')","('Punts', 'ATT')","('Punts', 'YDS')","('Punts', 'AVG')","('Punts', 'LNG')","('Punts', 'TD')","('Punts', 'FC')",PlayerID
0,13,25,664,26.6,66,0,28,223,8.0,22,0,15,Andre Roberts18
1,15,3,65,21.7,24,0,1,4,4.0,4,0,1,Isaiah McKenzie19
2,16,2,47,23.5,45,1,3,16,5.3,10,0,5,Micah Hyde23
3,16,1,24,24.0,24,0,0,0,0.0,0,0,0,Patrick DiMarco42
4,11,1,2,2.0,2,0,0,0,0.0,0,0,0,Senorise Perry
...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,16,20,428,21.4,81,0,33,264,8.0,32,0,11,Richie James Jr.13
150,16,14,279,19.9,33,0,13,66,5.1,20,0,10,Tyler Lockett16
151,16,5,109,21.8,29,0,0,0,0.0,0,0,0,Travis Homer25
152,10,3,44,14.7,21,0,0,0,0.0,0,0,0,Rashaad Penny20
153,14,0,0,0.0,0,0,10,75,7.5,18,0,10,David Moore83

In [21]:
owners_df = pd.read_csv("temp/owners_df.csv")
salary_df = pd.read_csv("temp/salary_df.csv")
stadium_df = pd.read_csv("temp/stadium_df.csv")
team_df = pd.read_csv("temp/team_df.csv")
team_table = pd.read_csv("temp/team_table.csv")

In [65]:
team_df

     TM                  Team
0   ARI     Arizona Cardinals
1   ATL       Atlanta Falcons
2   BAL      Baltimore Ravens
3   BUF         Buffalo Bills
4   CAR     Carolina Panthers
5   CHI         Chicago Bears
6   CIN    Cincinnati Bengals
7   CLE      Cleveland Browns
8   DAL        Dallas Cowboys
9   DEN        Denver Broncos
10  DET         Detroit Lions
11   GB     Green Bay Packers
12  HOU        Houston Texans
13  IND    Indianapolis Colts
14  JAX  Jacksonville Jaguars
15   KC    Kansas City Chiefs
16  LAC  Los Angeles Chargers
17  LAR      Los Angeles Rams
18   LV     Las Vegas Raiders
19  MIA        Miami Dolphins
20  MIN     Minnesota Vikings
21   NE  New England Patriots
22   NO    New Orleans Saints
23  NYG       New York Giants
24  NYJ         New York Jets
25  PHI   Philadelphia Eagles
26  PIT   Pittsburgh Steelers
27  SEA      Seattle Seahawks
28   SF   San Francisco 49ers
29   TB  Tampa Bay Buccaneers
30  TEN      Tennessee Titans
31  WAS   Washington Redskins

In [68]:
team_df.head()

    TM               Team
0  ARI  Arizona Cardinals
1  ATL    Atlanta Falcons
2  BAL   Baltimore Ravens
3  BUF      Buffalo Bills
4  CAR  Carolina Panthers

In [79]:
players_df.to_csv("temp/players_df.csv")

In [75]:
team_abv_list = []
for i in range(0,len(players_df.team)):
    x = True
    for j in range(0,len(team_df.Team)):
        
        if players_df.team[i] in team_df.Team[j] and x == True:
                   
            team_abv_list.append(team_df.TM[j])
            x=False
                   
            
            
team_abv_list

['BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'BUF',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'MIA',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NE',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'NYJ',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'BAL',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CIN',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'CLE',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'PIT',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'HOU',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'IND',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'JAX',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'TEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'DEN',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'KC',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LV',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'LAC',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'DAL',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'NYG',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'PHI',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'WAS',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'CHI',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'DET',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'GB',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'MIN',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 'ATL',
 ...]