In [21]:
from bs4 import *
import requests
import re
import pandas as pd

In [22]:
df = pd.read_csv("team_links.csv")

In [17]:
master_passing = pd.DataFrame({})
master_rushing = pd.DataFrame({})
master_receiving = pd.DataFrame({})
master_defense = pd.DataFrame({})
master_scoring = pd.DataFrame({})
master_returning = pd.DataFrame({})
master_kicking = pd.DataFrame({})
master_punting = pd.DataFrame({})

for i in range(0,len(df.Team)):
#for i in range(0,2):
    url = df.stat_links[i]
    table=pd.read_html(url)
    
    #collecting 12 tables
    if len(table[0])<2 or table[0].keys()[0]!='Name':
        table[0][table[14].keys()[0]]=table[0].keys()[0]
        table[0]=table[0].rename(columns={table[0].keys()[0]:"Name"})
    passing_df = table[0].merge(table[1],left_index=True, right_index=True)
    passing_df["class"]="Passing"
    passing_df["team"]=df.Team[i]
    if len(table[0])>1:    
        passing_df.drop(passing_df.tail(1).index,inplace=True)
    passing_df.reset_index()
    
    if len(table[2])<2 or table[2].keys()[0]!='Name':
        table[2][table[14].keys()[0]]=table[2].keys()[0]
        table[2]=table[2].rename(columns={table[2].keys()[0]:"Name"})
    rushing_df = table[2].merge(table[3],left_index=True, right_index=True)
    rushing_df["class"]="Rushing"
    rushing_df["team"]=df.Team[i]
    if len(table[2])>1:    
        rushing_df.drop(rushing_df.tail(1).index,inplace=True)
    rushing_df.reset_index()
    
    if len(table[4])<2 or table[4].keys()[0]!='Name':
        table[4][table[4].keys()[0]]=table[4].keys()[0]
        table[4]=table[4].rename(columns={table[4].keys()[0]:"Name"})
    receiving_df = table[4].merge(table[5],left_index=True, right_index=True)
    receiving_df["class"]="Receiving"
    receiving_df["team"]=df.Team[i]
    if len(table[4])>1:    
        receiving_df.drop(receiving_df.tail(1).index,inplace=True)
    receiving_df.reset_index()
    
    if len(table[6])<2 or table[6].keys()[0]!='Name':
        table[6][table[6].keys()[0]]=table[6].keys()[0]
        table[6]=table[6].rename(columns={table[6].keys()[0]:"Name"})
    defense_df = table[6].merge(table[7],left_index=True, right_index=True)
    defense_df["class"]="Defense"
    defense_df["team"]=df.Team[i]
    if len(table[6])>1:    
        defense_df.drop(defense_df.tail(1).index,inplace=True)
    defense_df.reset_index()
    
    if len(table[8])<2 or table[8].keys()[0]!='Name':
        table[8][table[8].keys()[0]]=table[8].keys()[0]
        table[8]=table[8].rename(columns={table[8].keys()[0]:"Name"})
    scoring_df = table[8].merge(table[9],left_index=True, right_index=True)
    scoring_df["class"]="Scoring"
    scoring_df["team"]=df.Team[i]
    if len(table[8])>1:    
        scoring_df.drop(scoring_df.tail(1).index,inplace=True)
    scoring_df.reset_index()
    
    if len(table[10])<2 or table[10].keys()[0]!='Name':
        table[10][table[10].keys()[0]]=table[10].keys()[0]
        table[10]=table[10].rename(columns={table[10].keys()[0]:"Name"})
    returning_df =table[10].merge(table[11],left_index=True, right_index=True)
    returning_df["class"]="Returning"
    returning_df["team"]=df.Team[i]
    if len(table[10])>1:    
        returning_df.drop(returning_df.tail(1).index,inplace=True)
    returning_df.reset_index()
    
    if len(table[12])<2 or  table[12].keys()[0]!='Name':
        table[12][table[12].keys()[0]]=table[12].keys()[0]
        table[12]=table[12].rename(columns={table[12].keys()[0]:"Name"})
    kicking_df = table[12].merge(table[13],left_index=True, right_index=True)
    kicking_df.reset_index()
    kicking_df["class"]="Kicking"
    kicking_df["team"]=df.Team[i]
    if len(table[12])>1:
        kicking_df.drop(kicking_df.tail(1).index,inplace=True)

    if len(table[14])<2 or table[14].keys()[0]!='Name':
        table[14][table[14].keys()[0]]=table[14].keys()[0]
        table[14]=table[14].rename(columns={table[14].keys()[0]:"Name"})
    punting_df = table[14].merge(table[15],left_index=True, right_index=True)
    punting_df.reset_index()
    punting_df["class"]="Punting"
    punting_df["team"]=df.Team[i]
    if len(table[14])>1:
        punting_df.drop(punting_df.tail(1).index,inplace=True)
    
    
    #merge all the tables into master DF
    master_passing=pd.concat([master_passing,passing_df])
    master_rushing=pd.concat([master_rushing,rushing_df])
    master_receiving=pd.concat([master_receiving,receiving_df])
    master_defense=pd.concat([master_defense,defense_df])
    master_scoring=pd.concat([master_scoring,scoring_df])
    master_returning=pd.concat([master_returning,returning_df])
    master_kicking=pd.concat([master_kicking,kicking_df])
    master_punting=pd.concat([master_punting,punting_df])

In [18]:
master_passing.to_csv("stats/passing.csv")
master_rushing.to_csv("stats/rushing.csv")
master_receiving.to_csv("stats/receiving.csv")

master_defense.to_csv("stats/defense.csv")
master_scoring.to_csv("stats/scoring.csv")
master_returning.to_csv("stats/returning.csv")

master_kicking.to_csv("stats/kicking.csv")
master_punting.to_csv("stats/punting.csv")

In [35]:
url = df.stat_links[2]
table=pd.read_html(url)
# if len(table[12])<2 or  table[12].keys()[0]!='Name':
#     table[12][table[12].keys()[0]]=table[12].keys()[0]
#     table[12]=table[12].rename(columns={table[12].keys()[0]:"Name"})
kicking_df = table[12].merge(table[13],left_index=True, right_index=True)
kicking_df.reset_index()
kicking_df["class"]="Kicking"
kicking_df["team"]=df.Team[2]
# if len(table[12])>1 and table[12].Name[-1]:
#     kicking_df.drop(kicking_df.tail(1).index,inplace=True)
kicking_df

,Nick Folk PK,"(Unnamed: 0_level_0, GP)","(Field Goals, FGM)","(Field Goals, FGA)","(Field Goals, FG%)","(Field Goals, LNG)","(Field Goals, 1-19)","(Field Goals, 20-29)","(Field Goals, 30-39)","(Field Goals, 40-49)","(Field Goals, 50+)","(Extra points, XPM)","(Extra points, XPA)","(Extra points, XP%)",class,team
0,Stephen Gostkowski PK,7,14,17,82.4,51,1-1,5-5,3-3,4-7,1-1,12,12,100.0,Kicking,Patriots
1,Mike Nugent PK,4,7,8,87.5,41,0-0,3-3,3-3,1-2,0-0,11,15,73.3,Kicking,Patriots
2,Kai Forbath PK,4,5,8,62.5,37,0-0,3-4,2-3,0-1,0-0,15,16,93.8,Kicking,Patriots
3,Total,1,1,1,100.0,23,0-0,1-1,0-0,0-0,0-0,1,2,50.0,Kicking,Patriots

                         0
index    Brandon Bolden RB
0           James White RB
1        Julian Edelman WR
2      Mohamed Sanu Sr. WR
3      Gunner Olszewski WR
4                    Total

In [51]:
table[11]

  Unnamed: 0_level_0 Kickoffs                   Punts
                  GP      ATT  YDS   AVG LNG TD   ATT  YDS  AVG LNG TD  FC
0                 15       23  515  22.4  38  0     0    0  0.0   0  0   0
1                 15        2   41  20.5  21  0     0    0  0.0   0  0   0
2                 16        1   19  19.0  19  0     0    0  0.0   0  0   0
3                  8        0    0   0.0   0  0     9   54  6.0  14  0   9
4                  8        0    0   0.0   0  0    20  179  8.9  22  0  16
5                 16       26  575  22.1  38  0    29  233  8.0  22  0  26